-- simple script to simulate FOC on BLDC motor

-- display console to print torque estimation and simulation progress
showconsole()
clearconsole()

-- open the fem file
mydir="./"
open(mydir .. "inductance_measure.fem")

-- save the fem file to another temporary file
-- the script will modify the rotor positions and winding currents during the simulation.  
mi_saveas(mydir .. "temp.fem")

-- set to edit mode to "group" so the rotor components can rotate as a "group".
-- refer to the femm user guide. 
mi_seteditmode("group")

-- set the bias current and delta_currents
-- measure the flux at bias_current + delta_current and at bias_current - delta_current 
-- difference between the flux readings is the flux generated due to the currents.
-- we need this 2 step process to account for the flux already generated by the magnets 
bias_current = 0.0;
delta_current = 0.5;

-- loop
for n=0,10 do
	
	-- calculate the 2 test-currents
	test_current_1 = bias_current + delta_current; 
	test_current_2 = bias_current - delta_current; 
	
	-- update to test_current_1 in phase to measure flux linkage
	mi_modifycircprop("A",1,test_current_1)
	mi_modifycircprop("B",1,-test_current_1 / 2.0)
	mi_modifycircprop("C",1,-test_current_1 / 2.0)

	-- run the solver, minimize window. 
    mi_analyze(1)
	-- After the solver is done, loads the solution 
    mi_loadsolution()
	
	-- flux is measured after test_current_1
	current_a,volts_a,flux_a_1 = mo_getcircuitproperties("A")
	
	-- redo the same process for the second test-current
	
	-- update to test_current_2 in phase to measure flux linkage
	mi_modifycircprop("A",1,test_current_2)
	mi_modifycircprop("B",1,-test_current_2 / 2.0)
	mi_modifycircprop("C",1,-test_current_2 / 2.0)

	-- run the solver, minimize window. 
    mi_analyze(1)
	-- After the solver is done, loads the solution 
    mi_loadsolution()
	
	-- flux is measured after test_current_2
	current_a,volts_a,flux_a_2 = mo_getcircuitproperties("A")

	-- estimate the inductance
	inductance = (flux_a_1 - flux_a_2) / (2.0*delta_current)
	
	-- adjsut screensize to get plots
	mo_resize(1200,1000)
	mo_zoom(-35,-35,35,35)
	
	-- show contour and density plots
    mo_showcontourplot(-1)
    mo_showdensityplot(1,0,2,0,"bmag")
	
	-- hide the plots after viewing. This makes the program more responsive
	mo_hidedensityplot()
    mo_hidecontourplot()
	
    print(bias_current,inductance)
	
	bias_current = bias_current + 5
	
end
mo_close()
mi_close()